In [1]:
import pandas as pd

In [2]:
cvd_data=pd.read_excel('Cumulative COVID Data.xlsx')

In [3]:
cvd_data

,State,District,2020-01-30 00:00:00,2020-01-31 00:00:00,2020-02-01 00:00:00,2020-02-02 00:00:00,2020-02-03 00:00:00,2020-02-04 00:00:00,2020-02-05 00:00:00,2020-02-06 00:00:00,...,2020-09-28 00:00:00,2020-09-29 00:00:00,2020-09-30 00:00:00,2020-10-01 00:00:00,2020-10-02 00:00:00,2020-10-03 00:00:00,2020-10-04 00:00:00,2020-10-05 00:00:00,2020-10-06 00:00:00,2020-10-07 00:00:00
0,Andhra Pradesh,Andhra Pradesh,0,0,0,0,0,0,0,0,...,681161,687351,693484,700235,706790,713014,719256,723512,729307,734427
1,Andhra Pradesh,Anantapur,0,0,0,0,0,0,0,0,...,56519,56795,57375,57708,58041,58323,58734,59005,59214,59638
2,Andhra Pradesh,Chittoor,0,0,0,0,0,0,0,0,...,60149,60933,61858,62746,63671,64498,65361,65585,66555,67362
3,Andhra Pradesh,East Godavari,0,0,0,0,0,0,0,0,...,95200,96191,97174,98160,99135,99959,100785,101638,102439,103246
4,Andhra Pradesh,Guntur,0,0,0,0,0,0,0,0,...,53782,54192,54690,55284,55735,56226,56788,57232,57673,58106
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
803,Puducherry,Karaikal,0,0,0,0,0,0,0,0,...,2393,2441,2517,2596,2596,2674,2727,2743,2832,2897
804,Puducherry,MahÃ©,0,0,0,0,0,0,0,0,...,263,273,283,303,303,318,380,380,414,471
805,Puducherry,Pondicherry,0,0,0,0,0,0,0,0,...,22402,22708,23077,23447,23878,24062,24269,24434,24698,25042
806,Puducherry,Yanam,0,0,0,0,0,0,0,0,...,1627,1644,1667,1678,1678,1698,1713,1720,1738,1751
807,Puducherry,Unknown,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
states=cvd_data[cvd_data['State']==cvd_data['District']]

In [5]:
states

,State,District,2020-01-30 00:00:00,2020-01-31 00:00:00,2020-02-01 00:00:00,2020-02-02 00:00:00,2020-02-03 00:00:00,2020-02-04 00:00:00,2020-02-05 00:00:00,2020-02-06 00:00:00,...,2020-09-28 00:00:00,2020-09-29 00:00:00,2020-09-30 00:00:00,2020-10-01 00:00:00,2020-10-02 00:00:00,2020-10-03 00:00:00,2020-10-04 00:00:00,2020-10-05 00:00:00,2020-10-06 00:00:00,2020-10-07 00:00:00
0,Andhra Pradesh,Andhra Pradesh,0,0,0,0,0,0,0,0,...,681161,687351,693484,700235,706790,713014,719256,723512,729307,734427
15,Arunachal Pradesh,Arunachal Pradesh,0,0,0,0,0,0,0,0,...,9332,9553,9796,10020,10220,10421,10548,10783,11007,11267
42,Assam,Assam,0,0,0,0,0,0,0,0,...,173629,177221,180811,182396,183812,185444,186200,187718,188902,190209
77,Bihar,Bihar,0,0,0,0,0,0,0,0,...,180032,181471,182906,184276,185707,186690,187951,188858,190123,191427
117,Chattisgarh,Chattisgarh,0,0,0,0,0,0,0,0,...,108458,110655,113602,116153,118790,121400,123324,126005,128893,131739
147,Goa,Goa,0,0,0,0,0,0,0,0,...,32396,32777,33418,33942,34455,34900,35328,35719,36238,36670
151,Gujarat,Gujarat,0,0,0,0,0,0,0,0,...,134461,135842,137232,138583,139893,141236,142538,143865,145200,146511
186,Haryana,Haryana,0,0,0,0,0,0,0,0,...,125447,127009,128634,129947,131423,132611,133913,134944,136150,137433
210,Himachal Pradesh,Himachal Pradesh,0,0,0,0,0,0,0,0,...,14457,14747,14976,15219,15454,15695,15851,16033,16283,16565
224,Jharkhand,Jharkhand,0,0,0,0,0,0,0,0,...,81417,82540,83651,84664,85400,86277,87210,88026,88873,89702
250,Karnataka,Karnataka,0,0,0,0,0,0,0,0,...,582458,592911,601767,611837,620630,630516,640661,647712,657705,668652
282,Kerala,Kerala,1,1,1,2,3,3,3,3,...,179922,187276,196106,204241,213499,221333,229886,234928,242799,253405
298,Madhya Pradesh,Madhya Pradesh,0,0,0,0,0,0,0,0,...,124166,126043,128047,130088,132107,133918,135638,137098,138668,140307
355,Maharashtra,Maharashtra,0,0,0,0,0,0,0,0,...,1351153,1366129,1384446,1400922,1416513,1430861,1443409,1453639,1465911,1480489
393,Manipur,Manipur,0,0,0,0,0,0,0,0,...,10477,10746,10983,11111,11397,11649,11855,12105,12240,12489
411,Meghalaya,Meghalaya,0,0,0,0,0,0,0,0,...,5360,5467,5641,5802,6037,6461,6655,6769,7036,7135
424,Mizoram,Mizoram,0,0,0,0,0,0,0,0,...,1958,1986,2017,2049,2103,2120,2120,2128,2147,2150
434,Nagaland,Nagaland,0,0,0,0,0,0,0,0,...,5957,6040,6163,6244,6318,6429,6552,6594,6662,6715
448,Odisha,Odisha,0,0,0,0,0,0,0,0,...,212609,215676,219119,222734,226334,229387,232713,235330,238003,240998
480,Punjab,Punjab,0,0,0,0,0,0,0,0,...,111375,112460,113886,115151,116213,117319,118157,119186,120016,120868
504,Rajasthan,Rajasthan,0,0,0,0,0,0,0,0,...,130971,133119,135292,137485,139696,141846,144030,146195,148316,150467
539,Sikkim,Sikkim,0,0,0,0,0,0,0,0,...,2815,2856,2931,2970,3012,3050,3093,3110,3135,3234
545,Tamil Nadu,Tamil Nadu,0,0,0,0,0,0,0,0,...,586397,591943,597602,603290,608885,614507,619996,625391,630408,635855
585,Telangana,Telangana,0,0,0,0,0,0,0,0,...,189283,191386,193600,195609,197327,199276,200611,202594,204748,206644
620,Tripura,Tripura,0,0,0,0,0,0,0,0,...,25350,25731,26063,26359,26549,26871,27030,27305,27542,27756
630,Uttar Pradesh,Uttar Pradesh,0,0,0,0,0,0,0,0,...,390875,394856,399082,403101,406995,410626,414466,417437,420937,424326
707,Uttarakhand,Uttarakhand,0,0,0,0,0,0,0,0,...,47502,47995,49000,49248,49559,50062,51481,51991,52329,52959
722,West Bengal,West Bengal,0,0,0,0,0,0,0,0,...,250580,253768,257049,260324,263634,266974,270331,273679,277049,280504
747,Andaman & Nicobar Islands,Andaman & Nicobar Islands,0,0,0,0,0,0,0,0,...,3803,3821,3835,3848,3858,3868,3884,3889,3902,3935
752,Chandigarh,Chandigarh,0,0,0,0,0,0,0,0,...,11678,11816,11938,12057,12212,12360,12445,12578,12707,12820
753,Chandigarh,Chandigarh,0,0,0,0,0,0,0,0,...,11678,11816,11938,12057,12212,12360,12445,12578,12707,12820
755,Dadra and Nagar Haveli and Daman and Diu,Dadra and Nagar Haveli and Daman and Diu,0,0,0,0,0,0,0,0,...,3003,3012,3032,3040,3061,3070,3087,3087,3096,3103
760,Jammu & Kashmir,Jammu & Kashmir,0,0,0,0,0,0,0,0,...,73014,74095,75070,76163,77253,78228,79106,79738,80476,81097
782,Ladakh,Ladakh,0,0,0,0,0,0,0,0,...,4152,4195,4269,4360,4429,4477,4521,4685,4720,4802
786,Lakshadweep,Lakshadweep,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
787,Lakshadweep,Lakshadweep,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
789,Delhi,Delhi,0,0,0,0,0,0,0,0,...,273098,276325,279715,282752,285672,287930,290613,292560,295236,298107
802,Puducherry,Puducherry,0,0,0,0,0,0,0,0,...,26685,27066,27544,28024,28455,28752,29089,29277,29682,30161

In [6]:
states.drop(index=752,inplace=True)

c:\users\abhijeet\appdata\local\programs\python\python38-32\lib\site-packages\pandas\core\frame.py:3990: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [7]:
states.drop(index=786,inplace=True)

In [8]:
states.index

Int64Index([  0,  15,  42,  77, 117, 147, 151, 186, 210, 224, 250, 282, 298,
            355, 393, 411, 424, 434, 448, 480, 504, 539, 545, 585, 620, 630,
            707, 722, 747, 753, 755, 760, 782, 787, 789, 802],
           dtype='int64')

In [9]:
cvd_data.drop(index=states.index,inplace=True)

In [10]:
unk_dist= cvd_data[cvd_data['District']=='Unknown']

In [11]:
cvd_data.drop(index=unk_dist.index,inplace=True)

In [12]:
cvd_data.to_excel('Cleaned COVID Cumulative Cases.xlsx')